#there will be 2 stages
#building that creates the dependencies and saves artifaces
#lining, to check that the code is all pretty as it should
#here would be the testing stage but i didnt had enough time

stages:
    - install
    - lint

install:
    stage: install
    image: mhart/alpine-node
    script:
        - npm install
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 30 mins
        paths:
            -node_modules

lint:
    stage: lint
    image: mhart/alpine-node
    script:
        - npm run eslint